export const blogPosts = [
  { slug: 'yak-pryskoriti-indeksaciyu-saitu-v-google', tag: 'Indexing', readTime: '10 minutes', title: 'How to speed up the indexing of your site in Google in 2025', desc: 'Step-by-step guide: from sitemap setup to Google Indexing API. Real methods that work.' },
  { slug: 'shcho-take-sitemap-xml', tag: 'SEO', readTime: '7 minutes', title: 'What is sitemap.xml and why does your site need it?', desc: 'Full breakdown: structure, types, mistakes and how to properly set up a sitemap for Google.' },
  { slug: 'google-indexing-api-vs-sitemap', tag: 'Indexing', readTime: '8 minutes', title: 'Google Indexing API vs sitemap: what works better?', desc: 'Comparison of two methods for getting pages into Google search.' },
  { slug: 'chomu-sait-ne-indeksuyetsya', tag: 'SEO', readTime: '6 minutes', title: 'Why your site is not indexed in Google: main reasons', desc: 'Common problems and their solutions for website owners.' },
  { slug: 'wordpress-indeksaciya', tag: 'WordPress', readTime: '9 minutes', title: 'How to index a WordPress site in Google: complete guide', desc: 'Practical tips for WordPress users to speed up indexing.' },
  { slug: 'seo-dlya-internet-magazynu', tag: 'E-commerce', readTime: '12 minutes', title: 'SEO for online stores: how to index thousands of products', desc: 'Strategies for large e-commerce sites with thousands of pages.' },
  { slug: 'on-page-seo-complete-guide-2026', tag: 'SEO', readTime: '15 minutes', title: 'On-page SEO complete guide for 2026', desc: 'Everything you need to know about on-page optimization.' },
  { slug: 'what-is-indexnow', tag: 'IndexNow', readTime: '5 minutes', title: 'What is IndexNow and how it complements Google indexing', desc: 'Introduction to the IndexNow protocol for Bing, Yandex and other search engines.' },
  { slug: 'core-web-vitals-2026', tag: 'Technical SEO', readTime: '10 minutes', title: 'Core Web Vitals in 2026: what changed and what to do', desc: 'Updated guide to Core Web Vitals and their impact on rankings.' },
  { slug: 'lokalne-seo', tag: 'SEO', readTime: '8 minutes', title: 'Local SEO: how to get clients from Google Maps', desc: 'Complete guide to local search optimization.' },
  { slug: 'backlink-building-for-small-business-2026', tag: 'Link Building', readTime: '11 minutes', title: 'Backlink building for small business in 2026', desc: 'Effective and safe link building strategies for small businesses.' },
  { slug: 'how-to-index-backlinks', tag: 'Indexing', readTime: '7 minutes', title: 'How to index backlinks quickly: proven methods', desc: 'Methods to get your backlinks indexed by Google faster.' },
  { slug: 'shvydkist-saitu-seo', tag: 'Technical SEO', readTime: '9 minutes', title: 'Site speed and SEO: how loading time affects rankings', desc: 'The relationship between page speed and search engine rankings.' },
  { slug: 'indeksaciya-pislya-redyzajnu', tag: 'SEO', readTime: '6 minutes', title: 'Indexing after redesign: how not to lose positions', desc: 'Checklist for maintaining rankings during and after a site redesign.' },
  { slug: 'cron-jobs-dlya-seo', tag: 'Automation', readTime: '8 minutes', title: 'Cron jobs for SEO: automating indexing tasks', desc: 'How to set up automated SEO tasks with cron jobs.' },
  { slug: 'seo-audit-checklyst', tag: 'SEO', readTime: '12 minutes', title: 'SEO audit checklist for 2026', desc: 'Complete checklist for auditing your website for SEO issues.' },
  { slug: 'avtomatychna-indeksaciya', tag: 'Automation', readTime: '10 minutes', title: 'Automated indexing: how it works and why it is needed', desc: 'The benefits and implementation of automated URL indexing.' },
  { slug: 'masova-indeksaciya-saitu', tag: 'Indexing', readTime: '7 minutes', title: 'Mass indexing of a site: rules and limitations', desc: 'How to index large numbers of URLs without hitting Google limits.' },
  { slug: 'google-search-console-posibnyk', tag: 'Guide', readTime: '14 minutes', title: 'Google Search Console guide for beginners', desc: 'Complete guide to using Google Search Console for SEO.' },
  { slug: 'yak-pereviriti-indeksaciyu-saitu', tag: 'SEO', readTime: '5 minutes', title: 'How to check if your site is indexed in Google', desc: 'Simple methods to verify your site\'s indexing status.' },
  { slug: 'indexfast-vs-omega-indexer', tag: 'Comparison', readTime: '8 minutes', title: 'IndexFast vs Omega Indexer: which is better?', desc: 'Detailed comparison of two popular indexing tools.' },
  { slug: 'indexfast-vs-speedyindex', tag: 'Comparison', readTime: '8 minutes', title: 'IndexFast vs SpeedyIndex: feature comparison', desc: 'Comparing features, pricing and results of both tools.' },
  { slug: 'yak-vybraty-drop-domen-dlya-pbn', tag: 'SEO', readTime: '10 minutes', title: 'How to choose an expired domain for PBN', desc: 'Guide to finding and evaluating expired domains for private blog networks.' },
  { slug: 'best-google-indexing-tools-2026', tag: 'Tools', readTime: '11 minutes', title: 'Best Google indexing tools in 2026', desc: 'Overview of the top tools for speeding up Google indexing.' },
  { slug: 'building-a-navigation-component', tag: 'Development', readTime: '6 minutes', title: 'Building a navigation component for modern sites', desc: 'Best practices for building accessible navigation components.' },
  { slug: 'create-a-landing-page-that-performs-great', tag: 'Design', readTime: '9 minutes', title: 'How to create a landing page that converts', desc: 'Design and optimization tips for high-converting landing pages.' },
  { slug: 'how-can-designers-prepare-for-the-future', tag: 'Design', readTime: '7 minutes', title: 'How designers can prepare for the future of web', desc: 'Skills and tools designers need for the evolving web landscape.' },
  { slug: 'how-to-create-an-effective-design-portfolio', tag: 'Design', readTime: '6 minutes', title: 'How to create an effective design portfolio', desc: 'Tips for designers to showcase their work effectively.' },
  { slug: 'starting-a-career-in-web-design', tag: 'Career', readTime: '8 minutes', title: 'Starting a career in web design in 2026', desc: 'Guide for aspiring web designers entering the industry.' },
  { slug: 'new-post', tag: 'News', readTime: '3 minutes', title: 'IndexFast news and updates', desc: 'Latest updates and news from the IndexFast team.' },
  { slug: 'post-template', tag: 'Template', readTime: '5 minutes', title: 'How to use IndexFast templates', desc: 'Getting started with IndexFast templates and workflows.' },
  { slug: 'blog-post-example', tag: 'Example', readTime: '4 minutes', title: 'Example blog post structure', desc: 'Example of how to structure your blog posts for SEO.' },
];
